Heasoft to 6.31 starting from ubuntu 22.04
sciserver/sciserver-compute-images pull request #20
Opened 2022-11-28 14:39 UTC by zoghbi-a

- Re-organized the build script to read the version numbers from a single json file for easy future updates.
- The base images use sciserver-essentials/3.0 (sciserver-base and sciserver-jupyter), which start from ubuntu 22.04
- Removed the heasoft version number from the name of the final folder.
- Some additional tweaks to reduce the size of the final image.

2022-11-28 19:24 UTC, esabol requested changes

2022-11-28 19:24 UTC, esabol commented on heasarc/README.md
> +In the folloing, each image starts with the image before it.
Typo on this line.

2022-11-28 19:24 UTC, esabol commented on heasarc/heasarc/entry.sh
> +exec "$@"
Missing carriage return (linefeed, technically) at the end of this line.

2022-11-28 19:24 UTC, esabol commented on heasarc/heasarc/kernel.json
> +}
Missing carriage return (linefeed, technically) at the end of this line.

2022-11-28 19:24 UTC, esabol commented on heasarc/xmmsas/Dockerfile
> +WORKDIR /home/${user}
Missing carriage return (linefeed, technically) at the end of this line.

2022-11-29 21:07 UTC, esabol approved these changes

2022-12-21 22:05 UTC, zoghbi-a commented
[fda4110](https://github.com/sciserver/sciserver-compute-images/pull/20/commits/fda4110329d7beed0fdd03d692e832a80b122b78) foces numpy=1.23 in ciao. The recent numpy=1.24 release breaks some tasks, so until the ciao team fixes that, downgrading numpy works for now.

2022-12-22 14:17 UTC, merged